sources:
  - name: compoundv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/compound-ethereum
  - name: aavev2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/aave-v2-ethereum