sources:
  - name: compoundv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/compound-ethereum
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: compoundv2Liquidates
  - name: aavev2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/aave-v2-ethereum
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: aavev2Liquidates
  - name: ironbank
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/iron-bank-ethereum
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: ironbankLiquidates
  - name: venus
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/venus-protocol-bsc
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: venusLiquidates
  - name: makerdao
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/makerdao-ethereum
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: makerdaoLiquidates
  - name: liquity
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/liquity-ethereum
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: liquityLiquidates
  - name: abracadabra
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/abracadabra-money-ethereum
    transforms:
      - autoPagination:
          validateSchema: true
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: abracadabraLiquidates
