sources:
  - name: compoundv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/compound-ethereum
    transforms:
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: compoundv2Liquidates
  - name: aavev2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/aave-v2-ethereum
    transforms:
      - rename:
          renames:
            - from:
                type: Query
                field: liquidates
              to:
                type: Query
                field: aavev2Liquidates
